<a href="https://colab.research.google.com/github/hub-mayank/Data-Science/blob/main/Lecture_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas (Day-2)**

**Creation & Display**

In [ ]:
import pandas as pd
dct = {
    'name' : ['Mayank', 'Rewas', 'Yogi', 'Bauna'],
    'age' : [20, 21, 16, 18],
    'roll no' : [1, 2, 3, 4]
}
df = pd.DataFrame(dct)    #creating dataframe
print(df)                 # just prints
display(df)               # displays very well
df1 = pd.DataFrame(dct, index=['a','b','c','d'])    #index handling
display(df1)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

**Information & Description**

In [98]:
df2 = pd.read_csv('student_data.csv')
df2.info()                #meta-data
df2.describe()            #it gives the count,mean,std,max,and in between percentage(25%,50%,75%) with accordance to columns.
# IQR - inter quartile range (q3 - q1) <--------> {q1 - 25%, q2 - 50, q3 - 75%}

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

**Data Handling**

In [99]:
df2 = pd.read_csv('student_data.csv')
display(df2.head(2))      #from starting
display(df2.tail(3))      #from last
display(df2.shape)        #gives the dimension
display(df2.columns)      #gives the list of columns
display(df2.index)        #gives the range of the indices

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.0,Placed
1,4,69,5,3,8,56,100.0,Placed

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

(10000, 8)

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

RangeIndex(start=0, stop=10000, step=1)

**Rows & Columns {iloc & loc}**

iloc works only on indices and loc works on labels too

iloc makes indexing of it's own but loc searches for the specific index

In [44]:
display(df2[['internet_usage', 'study_hours']])   #displaying specific rows
display(df2.study_hours) # -----> NOT recommended

df2.iloc[0:5]           #range of rows

df2.loc[df2['study_hours'] == 11, ['study_hours', 'sleep_hours']]
display(df2.loc[df2['study_hours'] == 11, ['study_hours', 'sleep_hours']].iloc[2:5])   #this is displaying the data with value of study_hours equal to 11 with columns - study_hours and sleep_hours, in which we are printing 2 to 5 rows (range)

      internet_usage  study_hours
0                  7            7
1                  3            4
2                  6           11
3                  8            8
4                  6            5
...              ...          ...
9995               7            2
9996               9            7
9997               5           10
9998               5           10
9999              11            2

[10000 rows x 2 columns]

0        7
1        4
2       11
3        8
4        5
        ..
9995     2
9996     7
9997    10
9998    10
9999     2
Name: study_hours, Length: 10000, dtype: int64

    study_hours  sleep_hours
10           11            8
29           11            9
30           11            5

**Assignment - 8**

In [55]:
display(df2.loc[df2['assignments_completed'] == 8,].iloc[1:2])

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
4,5,52,8,6,8,40,78.82,Placed

**Filtering**

In [97]:
df2[df2["assignments_completed"]>8].iloc[0:3]       #here the iloc is used to print within the range!!

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
6,10,40,4,11,9,50,98.12,Placed

**Adding new columns**

In [71]:
df2 = pd.read_csv("student_data.csv")
df2["age"] = 20
display(df2)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

**Renaming**

In [73]:
# df2 = pd.read_csv("student_data.csv")
df2 = df2.rename(columns={'assignments_completed':'mazdoori'})
df2 = df2.rename(columns={'age':'umar'})
display(df2)

,study_hours,attendance,sleep_hours,internet_usage,mazdoori,previous_score,exam_score,placement_status,umar
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

# **Operations on rows or column**

#axis=0    sort row indices
# axis=1    sort column names

In [94]:
df2 = pd.read_csv("student_data.csv")
df3 = df2.drop("attendance", axis=1)                             #removing rows or column
df0 = df2.drop([2,3])                                            #removing complete rows
df4 = df2.dropna()                                               #removing missing values
df5 = df2.sort_values(by = ['sleep_hours'], ascending=False)     #sort values by columns
df6 = df2.sort_index(axis=1)                                     #sort index (axis = 0: rows)(axis = 1: columns)
df7 = df2.isnull()                                               #check for missing values
df8 = df2.notnull()                                              #check for non-missing values
df9 = df2.fillna()                                               #fill missing values

display(df6)
# display(df3)
# display(df4)
# display(df5)
# display(df6)

,assignments_completed,attendance,exam_score,internet_usage,placement_status,previous_score,sleep_hours,study_hours
0,10,56,100.00,7,Placed,62,8,7
1,8,69,100.00,3,Placed,56,5,4
2,10,60,100.00,6,Placed,45,7,11
3,4,99,90.17,8,Placed,55,9,8
4,8,52,78.82,6,Placed,40,8,5
...,...,...,...,...,...,...,...,...
9995,8,58,69.31,7,Not Placed,88,9,2
9996,4,98,100.00,9,Placed,87,6,7
9997,10,44,95.94,5,Placed,37,8,10
9998,8,75,88.61,5,Placed,52,7,10
9999,16,70,78.96,11,Placed,52,6,2

In [96]:
df2 = pd.read_csv("student_data.csv")
display(df2.agg('assignments_completed'))

0       10
1        8
2       10
3        4
4        8
        ..
9995     8
9996     4
9997    10
9998     8
9999    16
Name: assignments_completed, Length: 10000, dtype: int64